name: .NET ATM CICD Pipeline
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '8.0.x'

    - name: Install Chrome dependencies
      run: |
          sudo apt-get update
          sudo apt-get install google-chrome-stable
          sudo apt-get install -y libglib2.0-0 libnss3 libfontconfig1
          google-chrome --version
          which google-chrome

      #run: |
        #sudo apt-get install -y wget unzip xvfb libxi6
        #sudo apt-get install -y google-chrome-stable

      #uses: browser-actions/setup-chrome@v1
      #with:
      #  chrome-version: 'stable'

    #- name: Setup ChromeDriver
    #  uses: nanasess/setup-chromedriver@v2

    - name: "Restore dependencies"
      run: dotnet restore
      working-directory: .

    - name: "Build"
      run: dotnet build --configuration Release --no-restore
      working-directory: .

    - name: "Run API tests"
      continue-on-error: true
      run: dotnet test --filter Category=API --configuration Release --no-build --verbosity normal
      working-directory: .

    - name: "Run UI tests"
      continue-on-error: true
      run: dotnet test --filter Category=UI --configuration Release --no-build --verbosity normal
      working-directory: .

    #- name: "Create folder for artifacts"
     # run: |
      #  mkdir -p $GITHUB_WORKSPACE/test-results
        
    - name: "Upload artifacts"
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshot
        path: |
          $GITHUB_WORKSPACE/bin/Debug/net8.0/*.png
        overwrite: true

    - name: "Upload k6 HTML Test Result"
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshot-with-brackets
        path: ${{ GITHUB_WORKSPACE }}/bin/Debug/8.0/*.png        
        overwrite: true
