name: .NET ATM CICD Pipeline
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser parameter supplied when running pipeline manually where to run the tests"
        required: true
        type: string
        default: 'chrome'

env:
  OUTPUT_DIR: $GITHUB_WORKSPACE/bin/Release/net8.0
  BROWSER: ${{ inputs.browser }}

jobs:
  build:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '8.0.x'

    - name: Install Chrome dependencies
      run: |
          sudo apt-get update
          sudo apt-get install google-chrome-stable
          sudo apt-get install -y libglib2.0-0 libnss3 libfontconfig1
          google-chrome --version
          which google-chrome

    - name: "Restore dependencies"
      run: dotnet restore
      working-directory: .

    - name: "Build"
      run: dotnet build --configuration Release --no-restore
      working-directory: .

    - name: "Run API tests"
      continue-on-error: true
      run: dotnet test --filter Category=API --configuration Release --no-build --verbosity normal
      working-directory: .

    - name: "Run UI tests"
      continue-on-error: true
      run: dotnet test --filter Category=UI --configuration Release --no-build --verbosity normal
      working-directory: .

    - name: "Upload artifacts"
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshot
        path: |
          $OUTPUT_DIR*.png
          $OUTPUT_DIR*.log
        overwrite: true
