name: .NET ATM CICD Pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  build:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '7.0.x'

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6 libconf-2-4
        sudo apt-get install -y google-chrome-stable
        google-chrome --version
        which google-chrome

    - name: "Restore dependencies"
      run: dotnet restore
      working-directory: .

    - name: "Build"
      run: dotnet build --configuration Release --no-restore
      working-directory: .

    - name: "Run tests"
      run: dotnet test --configuration Release --no-build --verbosity normal
      working-directory: .
