name: .NET ATM CICD Pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  build:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '8.0.x'

    - name: Install Chrome dependencies
      run: |
          sudo apt-get update
          sudo apt-get install google-chrome-stable
          sudo apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
          google-chrome --version
          which google-chrome

      #run: |
        #sudo apt-get update
        #sudo apt-get install -y wget unzip xvfb libxi6
        #sudo apt-get install -y google-chrome-stable
        #google-chrome --version
        #which google-chrome

      #uses: browser-actions/setup-chrome@v1
      #with:
      #  chrome-version: 'stable'

    #- name: Setup ChromeDriver
    #  uses: nanasess/setup-chromedriver@v2

    - name: "Restore dependencies"
      run: dotnet restore
      working-directory: .

    - name: "Build"
      run: dotnet build --configuration Release --no-restore
      working-directory: .

    - name: "Run tests"
      run: dotnet test --configuration Release --no-build --verbosity normal
      working-directory: .
